#!/bin/bash

# Splash
echo "Welcome to polytool! This is a proof of concept, bash-based, implementation of the PolyCraft build helper."
echo "PolyCraft is a work-in-progress build tool and dependency helper intended to make it easier to work with multi-repository projects and git-based dependencies."
echo
echo "Copyright(C) Nexus Internet Technologies 2026, released under the GPLv2 license. You should have a copy of the license under the .polytool folder of your project if you are using the wrapper."

# Check git
if ! command -v git &> /dev/null; then
    1>&2 echo Error: git is not installed, please make sure to install git prior to using polytool
    exit 1
fi

# Setup
chmod +x "$0"
runtimebasedir="$(dirname "$0")"

# Source main source
function sourceAll() {
    dir="$1"
    for subdir in "$dir"/*/; do
        if [ -d "$subdir" ]; then
            sourceAll "$subdir"
        fi
    done
    for file in "$dir"/*; do
        if [ -f "$file" ]; then
            source "$file"
        fi
    done
}
sourceAll "$runtimebasedir/src"

# Run
main "$@"
